import type { RotaResponse } from "@/types";

const MOCK_ROTAS: RotaResponse[] = [
  {
    id: "1",
    titulo: "Litoral Norte Potiguar",
    resumo: "Dunas, Parrachos de Maracajaú e praias de São Miguel do Gostoso.",
    descricao:
      "Roteiro clássico pelo litoral norte do RN: partindo de Natal, explore as dunas de Genipabu, mergulhe nos Parrachos de Maracajaú e encerre em São Miguel do Gostoso, conhecida pelos ventos ideais para kitesurf.",
    duracaoDias: 3,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "1-1",
        nome: "Genipabu",
        descricao: "Dunas móveis, buggy e lagoa de águas doces.",
        cidade: "Extremoz",
        latitude: -5.735,
        longitude: -35.21,
        ordem: 1,
      },
      {
        id: "1-2",
        nome: "Parrachos de Maracajaú",
        descricao: "Piscinas naturais de corais a cerca de 7 km da costa.",
        cidade: "Maracajaú",
        latitude: -5.4117,
        longitude: -35.2233,
        ordem: 2,
      },
      {
        id: "1-3",
        nome: "São Miguel do Gostoso",
        descricao: "Vila de pescadores com praias tranquilas e kitesurf.",
        cidade: "São Miguel do Gostoso",
        latitude: -5.1267,
        longitude: -35.6317,
        ordem: 3,
      },
    ],
  },
  {
    id: "2",
    titulo: "Pipa e Tibau do Sul",
    resumo: "Falésias, Golfinhos e pôr do sol no litoral sul.",
    descricao:
      "Descubra a Praia de Pipa, uma das mais famosas do Brasil, com falésias coloridas, golfinhos na Baía dos Golfinhos e a charmosa vila de Tibau do Sul ao lado.",
    duracaoDias: 2,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "2-1",
        nome: "Praia de Pipa",
        descricao: "Falésias, restaurantes e vida noturna à beira-mar.",
        cidade: "Tibau do Sul",
        latitude: -6.2283,
        longitude: -35.0433,
        ordem: 1,
      },
      {
        id: "2-2",
        nome: "Baía dos Golfinhos",
        descricao: "Observação de golfinos-rotadores em seu habitat natural.",
        cidade: "Tibau do Sul",
        latitude: -6.215,
        longitude: -35.035,
        ordem: 2,
      },
      {
        id: "2-3",
        nome: "Praia do Madeiro",
        descricao: "Enseada protegida ideal para famílias e iniciantes no surf.",
        cidade: "Tibau do Sul",
        latitude: -6.24,
        longitude: -35.05,
        ordem: 3,
      },
    ],
  },
  {
    id: "3",
    titulo: "Natal — Cidade do Sol",
    resumo: "Orla urbana, Forte dos Reis Magos e artesanato potiguar.",
    descricao:
      "Passeio urbano por Natal: Forte dos Reis Magos, Ponta Negra, Morro do Careca, Mercado de Artesanato e o famoso pôr do sol na Via Costeira.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "3-1",
        nome: "Forte dos Reis Magos",
        descricao: "Fortaleza do século XVI na margem do Rio Potengi.",
        cidade: "Natal",
        latitude: -5.7636,
        longitude: -35.1944,
        ordem: 1,
      },
      {
        id: "3-2",
        nome: "Ponta Negra",
        descricao: "Praia urbana com o icônico Morro do Careca ao fundo.",
        cidade: "Natal",
        latitude: -5.8833,
        longitude: -35.1806,
        ordem: 2,
      },
      {
        id: "3-3",
        nome: "Mercado de Artesanato",
        descricao: "Artesanato local, renda e culinária típica potiguar.",
        cidade: "Natal",
        latitude: -5.7945,
        longitude: -35.211,
        ordem: 3,
      },
    ],
  },
  {
    id: "4",
    titulo: "Costa Branca e Galinhos",
    resumo: "Praias desertas, salinas e o charme de Galinhos.",
    descricao:
      "Aventura pela Costa Branca: de Macau às salinas, atravessando dunas até a península de Galinhos, um dos destinos mais preservados do litoral potiguar.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "4-1",
        nome: "Macau",
        descricao: "Praias amplas e dunas na Costa Branca.",
        cidade: "Macau",
        latitude: -5.1119,
        longitude: -36.6344,
        ordem: 1,
      },
      {
        id: "4-2",
        nome: "Salinas de Galinhos",
        descricao: "Paisagem de sal e dunas na península.",
        cidade: "Galinhos",
        latitude: -5.09,
        longitude: -36.2767,
        ordem: 2,
      },
      {
        id: "4-3",
        nome: "Centro de Galinhos",
        descricao: "Vila de pescadores acessível apenas por barco ou dunas.",
        cidade: "Galinhos",
        latitude: -5.085,
        longitude: -36.27,
        ordem: 3,
      },
    ],
  },
  {
    id: "5",
    titulo: "Sertão Potiguar",
    resumo: "Mossoró, cultura do algodão e o sertão nordestino.",
    descricao:
      "Conheça o interior do RN: Mossoró com seu museu do petróleo, a cultura do algodão e as paisagens únicas do sertão semiárido potiguar.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "5-1",
        nome: "Mossoró — Centro Histórico",
        descricao: "Cidade do Lampião e berço da indústria petrolífera no RN.",
        cidade: "Mossoró",
        latitude: -5.1875,
        longitude: -37.3444,
        ordem: 1,
      },
      {
        id: "5-2",
        nome: "Museu do Petróleo",
        descricao: "História da exploração petrolífera no Rio Grande do Norte.",
        cidade: "Mossoró",
        latitude: -5.19,
        longitude: -37.35,
        ordem: 2,
      },
      {
        id: "5-3",
        nome: "Praia de Mossoró (Boa Vista)",
        descricao: "Balneário no sertão com águas termais e lagoa.",
        cidade: "Mossoró",
        latitude: -5.15,
        longitude: -37.3,
        ordem: 3,
      },
    ],
  },
  {
    id: "6",
    titulo: "Canguaretama e Litoral Extremo Sul",
    resumo: "Praias selvagens entre RN e PB.",
    descricao:
      "Rota pelo extremo sul do estado: praias pouco exploradas de Canguaretama e Barra de Cunhaú, ideais para quem busca tranquilidade.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "rascunho",
    destaque: false,
    pontos: [
      {
        id: "6-1",
        nome: "Barra de Cunhaú",
        descricao: "Estuário com manguezais e camarão fresco.",
        cidade: "Canguaretama",
        latitude: -6.35,
        longitude: -35.05,
        ordem: 1,
      },
      {
        id: "6-2",
        nome: "Praia de Cabaço",
        descricao: "Praia extensa e pouco movimentada no litoral sul.",
        cidade: "Canguaretama",
        latitude: -6.38,
        longitude: -35.08,
        ordem: 2,
      },
    ],
  },
  {
    id: "7",
    titulo: "Tangará — Capital Gastronômica do Pastel",
    resumo: "Patrimônio cultural imaterial do RN: pastel de massa regional na BR-226.",
    descricao:
      "Tangará é parada obrigatória na BR-226 entre Natal e o Seridó. A cidade se tornou referência nacional pelo pastel de massa própria, reconhecido como patrimônio cultural imaterial do Rio Grande do Norte. Pastelarias à beira da rodovia, festival gastronômico e tradição desde os anos 1960.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "7-1",
        nome: "Centro e BR-226",
        descricao: "Corredor de pastelarias e restaurantes tradicionais à margem da rodovia.",
        cidade: "Tangará",
        latitude: -6.1981,
        longitude: -37.005,
        ordem: 1,
      },
      {
        id: "7-2",
        nome: "Restaurante Veneza",
        descricao: "Desde 1969, um dos pioneiros do legítimo pastel de Tangará.",
        cidade: "Tangará",
        latitude: -6.1995,
        longitude: -37.0038,
        ordem: 2,
      },
      {
        id: "7-3",
        nome: "Festival Gastronômico do Pastel",
        descricao: "Evento anual que celebra a identidade culinária do município.",
        cidade: "Tangará",
        latitude: -6.1975,
        longitude: -37.0065,
        ordem: 3,
      },
    ],
  },
  {
    id: "8",
    titulo: "Carnaubais — Cidade Histórica do Potengi",
    resumo: "Patrimônio colonial, casarões e memória da colonização potiguar.",
    descricao:
      "Carnaubais preserva o charme das cidades históricas do interior do RN. Casarões do século XIX, igrejas centenárias e ruas de paralelepípedo contam a história da colonização às margens do Rio Potengi. Ideal para turismo cultural e fotografia.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "8-1",
        nome: "Centro Histórico",
        descricao: "Casarões coloniais e arquitetura preservada do sertão do Potengi.",
        cidade: "Carnaubais",
        latitude: -5.3408,
        longitude: -36.8358,
        ordem: 1,
      },
      {
        id: "8-2",
        nome: "Igreja Matriz",
        descricao: "Templo centenário no coração da cidade histórica.",
        cidade: "Carnaubais",
        latitude: -5.3415,
        longitude: -36.8345,
        ordem: 2,
      },
      {
        id: "8-3",
        nome: "Margens do Rio Potengi",
        descricao: "Paisagem fluvial e tradição ribeirinha do município.",
        cidade: "Carnaubais",
        latitude: -5.338,
        longitude: -36.832,
        ordem: 3,
      },
    ],
  },
  {
    id: "9",
    titulo: "Cerro Corá — Memorial da História",
    resumo: "Batalha de Cerro Corá e paisagens do Seridó Oriental.",
    descricao:
      "Cerro Corá guarda a memória da última batalha de Lampião e Maria Bonita, em 1938. O município combina turismo histórico com paisagens de serras e clima ameno do Seridó Oriental.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "9-1",
        nome: "Memorial da Batalha",
        descricao: "Local histórico da última batalha do cangaço no Nordeste.",
        cidade: "Cerro Corá",
        latitude: -6.0464,
        longitude: -36.3478,
        ordem: 1,
      },
      {
        id: "9-2",
        nome: "Centro de Cerro Corá",
        descricao: "Praça central e comércio típico do Seridó.",
        cidade: "Cerro Corá",
        latitude: -6.05,
        longitude: -36.35,
        ordem: 2,
      },
    ],
  },
  {
    id: "10",
    titulo: "Martins — Serra Fria Potiguar",
    resumo: "Clima de montanha, vinhedos e gastronomia serrana no oeste do RN.",
    descricao:
      "Martins é conhecida como a cidade mais fria do Rio Grande do Norte. Situada na Serra de Martins, oferece clima ameno, produção de vinhos artesanais, queijos e paisagens verdes incomuns no sertão.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "10-1",
        nome: "Serra de Martins",
        descricao: "Mirantes com vista panorâmica e temperaturas mais baixas.",
        cidade: "Martins",
        latitude: -6.0831,
        longitude: -37.9167,
        ordem: 1,
      },
      {
        id: "10-2",
        nome: "Vinícolas Artesanais",
        descricao: "Produção de vinhos e derivados de uva na serra potiguar.",
        cidade: "Martins",
        latitude: -6.09,
        longitude: -37.91,
        ordem: 2,
      },
      {
        id: "10-3",
        nome: "Centro de Martins",
        descricao: "Gastronomia serrana, artesanato e clima de refúgio.",
        cidade: "Martins",
        latitude: -6.08,
        longitude: -37.92,
        ordem: 3,
      },
    ],
  },
  {
    id: "11",
    titulo: "Currais Novos — Águas Termais",
    resumo: "Balneário termal e portal de entrada para o Seridó.",
    descricao:
      "Currais Novos é famosa pelas águas termais medicinais e pelo papel de entroncamento rodoviário do Seridó. Combina lazer em piscinas naturais aquecidas com a cultura do interior potiguar.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "11-1",
        nome: "Balneário Termal",
        descricao: "Piscinas de águas quentes com propriedades terapêuticas.",
        cidade: "Currais Novos",
        latitude: -6.2608,
        longitude: -36.5158,
        ordem: 1,
      },
      {
        id: "11-2",
        nome: "Centro de Currais Novos",
        descricao: "Comércio regional e culinária típica do Seridó.",
        cidade: "Currais Novos",
        latitude: -6.265,
        longitude: -36.52,
        ordem: 2,
      },
    ],
  },
  {
    id: "12",
    titulo: "Acari — Lajedo de Soledade",
    resumo: "Formações rochosas milenares e sítios arqueológicos no sertão.",
    descricao:
      "Acari abriga o Lajedo de Soledade, impressionante formação rochosa com inscrições rupestres e trilhas entre blocos de granito. Um dos destinos naturais mais singulares do interior do RN.",
    duracaoDias: 1,
    dificuldade: "moderada",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "12-1",
        nome: "Lajedo de Soledade",
        descricao: "Formações rochosas e arte rupestre em área de preservação.",
        cidade: "Acari",
        latitude: -6.4289,
        longitude: -36.6403,
        ordem: 1,
      },
      {
        id: "12-2",
        nome: "Centro de Acari",
        descricao: "Base para explorar o sertão central potiguar.",
        cidade: "Acari",
        latitude: -6.435,
        longitude: -36.635,
        ordem: 2,
      },
    ],
  },
  {
    id: "13",
    titulo: "São Tomé — Cânions do Potengi",
    resumo: "Desfiladeiros, piscinas naturais e ecoturismo no Seridó.",
    descricao:
      "São Tomé é destino de ecoturismo no Seridó Oriental, com cânions esculpidos pelo Rio Potengi, trilhas e piscinas naturais em meio à caatinga. Aventura e natureza no interior do estado.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "13-1",
        nome: "Cânion do Potengi",
        descricao: "Desfiladeiros rochosos e trilhas com vista espetacular.",
        cidade: "São Tomé",
        latitude: -5.9728,
        longitude: -36.0789,
        ordem: 1,
      },
      {
        id: "13-2",
        nome: "Piscinas Naturais",
        descricao: "Poços de água cristalina entre formações rochosas.",
        cidade: "São Tomé",
        latitude: -5.98,
        longitude: -36.07,
        ordem: 2,
      },
    ],
  },
  {
    id: "14",
    titulo: "Pau dos Ferros — Coração do Seridó",
    resumo: "Cultura sertaneja, feiras e tradições do interior potiguar.",
    descricao:
      "Pau dos Ferros é um dos principais polos urbanos do Seridó, com feira livre tradicional, artesanato regional e proximidade às serras de Martins e Portalegre. Ponto de partida para explorar o oeste do RN.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "14-1",
        nome: "Feira Livre",
        descricao: "Produtos regionais, artesanato e comida típica do Seridó.",
        cidade: "Pau dos Ferros",
        latitude: -6.1094,
        longitude: -38.2083,
        ordem: 1,
      },
      {
        id: "14-2",
        nome: "Centro de Pau dos Ferros",
        descricao: "Praças, comércio e vida urbana do sertão potiguar.",
        cidade: "Pau dos Ferros",
        latitude: -6.115,
        longitude: -38.21,
        ordem: 2,
      },
    ],
  },
  {
    id: "15",
    titulo: "Caicó — Portal do Seridó",
    resumo: "História, comércio e acesso às rotas do sertão central.",
    descricao:
      "Caicó é entroncamento estratégico do Seridó, com patrimônio histórico, mercado regional e fácil acesso a destinos como Acari, Currais Novos e São Tomé. Ideal como base para roteiros pelo interior.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "15-1",
        nome: "Centro Histórico de Caicó",
        descricao: "Edificações centenárias e memória do Seridó.",
        cidade: "Caicó",
        latitude: -6.4583,
        longitude: -37.0978,
        ordem: 1,
      },
      {
        id: "15-2",
        nome: "Mercado Municipal",
        descricao: "Produtos do sertão: mel, caju, queijos e artesanato.",
        cidade: "Caicó",
        latitude: -6.46,
        longitude: -37.095,
        ordem: 2,
      },
    ],
  },
  {
    id: "16",
    titulo: "Rota dos Vinhos — Equador e Alexandria",
    resumo: "Vinhedos artesanais e enoturismo no sertão do RN.",
    descricao:
      "Equador e Alexandria formam a rota enogastronômica do Rio Grande do Norte. Pequenas vinícolas familiares produzem vinhos, sucos e licores de uva e frutas regionais, aproveitando o clima favorável do sertão.",
    duracaoDias: 2,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "16-1",
        nome: "Vinícolas de Equador",
        descricao: "Degustação de vinhos artesanais e suco de uva.",
        cidade: "Equador",
        latitude: -6.9467,
        longitude: -36.73,
        ordem: 1,
      },
      {
        id: "16-2",
        nome: "Produção Vitivinícola de Alexandria",
        descricao: "Vinhedos familiares e produtos derivados de uva.",
        cidade: "Alexandria",
        latitude: -6.4144,
        longitude: -36.6086,
        ordem: 2,
      },
    ],
  },
  {
    id: "17",
    titulo: "Jucurutu — Pedra do Sunga",
    resumo: "Formação rochosa icônica e trilhas no Seridó Ocidental.",
    descricao:
      "Jucurutu é conhecida pela Pedra do Sunga, imponente monólito que domina a paisagem do Seridó Ocidental. Trilhas, mirantes e contato com a caatinga potiguar.",
    duracaoDias: 1,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "17-1",
        nome: "Pedra do Sunga",
        descricao: "Formação rochosa emblemática com trilha e mirante.",
        cidade: "Jucurutu",
        latitude: -6.0339,
        longitude: -37.0194,
        ordem: 1,
      },
      {
        id: "17-2",
        nome: "Centro de Jucurutu",
        descricao: "Base para explorar o Seridó Ocidental.",
        cidade: "Jucurutu",
        latitude: -6.04,
        longitude: -37.02,
        ordem: 2,
      },
    ],
  },
  {
    id: "18",
    titulo: "Serra Negra do Norte — Refúgio na Serra",
    resumo: "Clima ameno, trilhas e tranquilidade no Seridó.",
    descricao:
      "Serra Negra do Norte oferece temperaturas mais baixas e paisagens verdes na transição entre sertão e serra. Destino tranquilo para quem busca descanso e contato com a natureza do interior.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "18-1",
        nome: "Mirante da Serra",
        descricao: "Vista panorâmica do Seridó a partir das serras.",
        cidade: "Serra Negra do Norte",
        latitude: -6.6167,
        longitude: -37.3833,
        ordem: 1,
      },
      {
        id: "18-2",
        nome: "Centro da Cidade",
        descricao: "Clima agradável e hospitalidade sertaneja.",
        cidade: "Serra Negra do Norte",
        latitude: -6.62,
        longitude: -37.38,
        ordem: 2,
      },
    ],
  },
  {
    id: "19",
    titulo: "Apodi — Vale do Apodi",
    resumo: "Cachoeiras, serra de Santana e o oeste semiárido do RN.",
    descricao:
      "Apodi fica no vale do Rio Apodi, entre Mossoró e o sertão profundo. Cachoeiras sazonais, a Serra de Santana e a cultura do algodão e do gado compõem um roteiro autêntico do interior oeste.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "19-1",
        nome: "Serra de Santana",
        descricao: "Formação montanhosa com trilhas e mirantes.",
        cidade: "Apodi",
        latitude: -5.6636,
        longitude: -37.7978,
        ordem: 1,
      },
      {
        id: "19-2",
        nome: "Cachoeiras do Apodi",
        descricao: "Quedas d'água sazonais no vale do rio homônimo.",
        cidade: "Apodi",
        latitude: -5.67,
        longitude: -37.79,
        ordem: 2,
      },
    ],
  },
  {
    id: "20",
    titulo: "Santa Cruz — Segunda Cidade do RN",
    resumo: "Patrimônio histórico e tradição religiosa no Seridó.",
    descricao:
      "Santa Cruz é a segunda cidade mais antiga do Rio Grande do Norte, fundada em 1832. Igrejas históricas, casarões coloniais e forte tradição religiosa a tornam referência em turismo cultural do interior.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "20-1",
        nome: "Centro Histórico",
        descricao: "Casarões e ruas que preservam a memória colonial potiguar.",
        cidade: "Santa Cruz",
        latitude: -6.2297,
        longitude: -36.0217,
        ordem: 1,
      },
      {
        id: "20-2",
        nome: "Igreja Matriz",
        descricao: "Templo centenário e ponto central da devoção local.",
        cidade: "Santa Cruz",
        latitude: -6.231,
        longitude: -36.02,
        ordem: 2,
      },
    ],
  },
  {
    id: "21",
    titulo: "Lagoa Nova — Terra dos Dinossauros",
    resumo: "Fósseis, paleontologia e sítios pré-históricos no Seridó.",
    descricao:
      "Lagoa Nova é referência em paleontologia no Nordeste. Fósseis de dinossauros e outros vertebrados pré-históricos foram encontrados na região, atraindo pesquisadores e curiosos para conhecer a história geológica do sertão.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: true,
    pontos: [
      {
        id: "21-1",
        nome: "Sítios Paleontológicos",
        descricao: "Áreas com fósseis de dinossauros e répteis pré-históricos.",
        cidade: "Lagoa Nova",
        latitude: -6.1044,
        longitude: -36.4858,
        ordem: 1,
      },
      {
        id: "21-2",
        nome: "Centro de Lagoa Nova",
        descricao: "Base para visitar a região paleontológica do Seridó.",
        cidade: "Lagoa Nova",
        latitude: -6.11,
        longitude: -36.49,
        ordem: 2,
      },
    ],
  },
  {
    id: "22",
    titulo: "Portalegre — Serra de Portalegre",
    resumo: "Montanhas, clima fresco e trilhas no extremo oeste do RN.",
    descricao:
      "Portalegre situa-se na Serra de Portalegre, próxima à divisa com o Ceará. Clima ameno, trilhas e paisagens verdes contrastam com o sertão ao redor, ideal para ecoturismo de montanha.",
    duracaoDias: 2,
    dificuldade: "moderada",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "22-1",
        nome: "Serra de Portalegre",
        descricao: "Trilhas e mirantes na serra que divide RN e CE.",
        cidade: "Portalegre",
        latitude: -6.0267,
        longitude: -37.9878,
        ordem: 1,
      },
      {
        id: "22-2",
        nome: "Centro de Portalegre",
        descricao: "Cidade serrana com gastronomia e artesanato regional.",
        cidade: "Portalegre",
        latitude: -6.03,
        longitude: -37.99,
        ordem: 2,
      },
    ],
  },
  {
    id: "23",
    titulo: "Bodó — Capital do Cajueiro",
    resumo: "Maior cajueiro do mundo e festa do caju no sertão.",
    descricao:
      "Bodó abriga um dos maiores cajueiros do planeta, árvore centenária com copa gigantesca. O município celebra a cultura do caju com festas, derivados da fruta e paisagens típicas da caatinga potiguar.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "23-1",
        nome: "Maior Cajueiro",
        descricao: "Árvore centenária com copa de mais de 8 mil m².",
        cidade: "Bodó",
        latitude: -5.7486,
        longitude: -36.4031,
        ordem: 1,
      },
      {
        id: "23-2",
        nome: "Centro de Bodó",
        descricao: "Produtos à base de caju: sucos, doces e cachaça.",
        cidade: "Bodó",
        latitude: -5.75,
        longitude: -36.4,
        ordem: 2,
      },
    ],
  },
  {
    id: "24",
    titulo: "Nova Cruz — Agreste Potiguar",
    resumo: "Feira tradicional, artesanato e cultura do agreste central.",
    descricao:
      "Nova Cruz é polo do agreste potiguar entre Natal e o sertão. Feira livre animada, produção de rapadura, artesanato em couro e proximidade a destinos como Goianinha e Canguaretama.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "24-1",
        nome: "Feira de Nova Cruz",
        descricao: "Um dos mercados mais tradicionais do agreste potiguar.",
        cidade: "Nova Cruz",
        latitude: -6.4781,
        longitude: -35.4339,
        ordem: 1,
      },
      {
        id: "24-2",
        nome: "Centro de Nova Cruz",
        descricao: "Comércio regional e culinária típica do agreste.",
        cidade: "Nova Cruz",
        latitude: -6.48,
        longitude: -35.43,
        ordem: 2,
      },
    ],
  },
  {
    id: "25",
    titulo: "João Câmara — Sertão do Agreste",
    resumo: "Paisagens de transição entre litoral e sertão profundo.",
    descricao:
      "João Câmara marca a transição entre o agreste e o sertão do RN. Açudes, roças de caju e a cultura sertaneja autêntica fazem do município uma parada interessante no caminho para o interior.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "25-1",
        nome: "Açude público",
        descricao: "Lazer às margens do reservatório no coração do município.",
        cidade: "João Câmara",
        latitude: -5.5375,
        longitude: -35.8197,
        ordem: 1,
      },
      {
        id: "25-2",
        nome: "Centro de João Câmara",
        descricao: "Vida sertaneja, feira e gastronomia local.",
        cidade: "João Câmara",
        latitude: -5.54,
        longitude: -35.82,
        ordem: 2,
      },
    ],
  },
  {
    id: "26",
    titulo: "Umarizal — Mel e Sertão Verde",
    resumo: "Apicultura, mel silvestre e paisagens do oeste potiguar.",
    descricao:
      "Umarizal destaca-se pela produção de mel de excelência no sertão do RN. Apiários, mel silvestre e a paisagem semiárida com vegetação de caatinga compõem roteiro gourmand pelo interior oeste.",
    duracaoDias: 1,
    dificuldade: "facil",
    status: "ativa",
    destaque: false,
    pontos: [
      {
        id: "26-1",
        nome: "Apiários Locais",
        descricao: "Produção artesanal de mel silvestre e própolis.",
        cidade: "Umarizal",
        latitude: -5.9906,
        longitude: -37.8144,
        ordem: 1,
      },
      {
        id: "26-2",
        nome: "Centro de Umarizal",
        descricao: "Degustação de mel e produtos apícolas regionais.",
        cidade: "Umarizal",
        latitude: -5.995,
        longitude: -37.81,
        ordem: 2,
      },
    ],
  },
];

export const rotaService = {
  listar: async (): Promise<RotaResponse[]> => {
    await new Promise((resolve) => setTimeout(resolve, 400));
    return MOCK_ROTAS;
  },

  listarAtivas: async (): Promise<RotaResponse[]> => {
    await new Promise((resolve) => setTimeout(resolve, 400));
    return MOCK_ROTAS.filter((r) => r.status === "ativa");
  },

  buscarPorId: async (id: string): Promise<RotaResponse | undefined> => {
    await new Promise((resolve) => setTimeout(resolve, 200));
    return MOCK_ROTAS.find((r) => r.id === id);
  },
};
